repos:
    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.9.26
      hooks:
          - id: uv-lock # Lock the dependencies
            args: ["-p", "3.14"]
          - id: uv-sync # Sync the dependencies
            args: ["-p", "3.14"]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.10
      hooks:
          - id: ruff # Lint code with ruff
            args: ["--fix", "--unsafe-fixes"]
          - id: ruff-format # Format code with ruff

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-added-large-files # Prevent giant files from being committed
          - id: check-ast # Check whether files parse as valid python.
          - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows.
          - id: check-docstring-first # Check no code before the file docstring
          - id: check-json # Load any json files to verify syntax
          - id: check-merge-conflict # Check for files that contain merge conflict strings
          - id: check-toml # Load any toml files to verify syntax
          - id: check-yaml # Load any yaml files to verify syntax
          - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
          - id: mixed-line-ending # Replaces or checks mixed line ending
            args: ["--fix=lf"]
          - id: name-tests-test # verifies that test files are named correctly
            args: ["--pytest-test-first"]
          - id: trailing-whitespace # Trims trailing whitespace, except for markdown file hard line breaks
            args: ["--markdown-linebreak-ext=md"]
